name: pace_app
description: University project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: packages/cache
    
  animated_text_kit: ^4.2.1
  basic_utils: 3.1.0
  bloc: 7.0.0
  cloud_firestore: ^2.2.2
  cupertino_icons: ^1.0.3
  equatable: ^2.0.2
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  fl_chart: 0.36.1
  flow_builder: 0.0.2
  flutter_bloc: ^7.0.1
  flutter_easyloading: 3.0.0
  fluttertoast: ^8.0.7
  formz: 0.4.0
  freezed_annotation: 0.14.2
  get: 4.1.4
  get_it: 7.1.3
  injectable: 1.4.1
  mockito: 5.0.10
  provider: 5.0.0
  settings_ui: ^1.0.0
  shared_preferences: ^2.0.6
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.0.4
  freezed: 0.14.2
  injectable_generator: 1.4.1

flutter:
  uses-material-design: true

  assets:
    - images/
