name: pace_app
description: University project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: packages/cache
  animated_text_kit: ^4.2.0
  bloc: ^7.0.0
  cloud_firestore: ^1.0.4
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  fl_chart: ^0.36.1
  flow_builder: ^0.0.2
  flutter_bloc: ^7.0.0
  flutter_easyloading: ^3.0.0
  fluttertoast: ^8.0.6
  formz: ^0.4.0
  freezed_annotation: ^0.14.1
  get: ^4.1.4
  get_it: ^6.1.1
  injectable: ^1.2.2
  provider: ^5.0.0
  basic_utils: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  freezed: ^0.14.1+2
  injectable_generator: ^1.2.2

flutter:

  uses-material-design: true

  assets:
    - images/
